/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicTermsRouteImport } from './routes/_public.terms'
import { Route as PublicPromptExpertsRouteImport } from './routes/_public.prompt-experts'
import { Route as PublicPrivacyRouteImport } from './routes/_public.privacy'
import { Route as PublicPricingRouteImport } from './routes/_public.pricing'
import { Route as PublicFeaturesRouteImport } from './routes/_public.features'
import { Route as PublicFaqRouteImport } from './routes/_public.faq'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardHistoryRouteImport } from './routes/_dashboard.history'
import { Route as DashboardHelpRouteImport } from './routes/_dashboard.help'
import { Route as DashboardFavoritesRouteImport } from './routes/_dashboard.favorites'
import { Route as DashboardExpertsRouteImport } from './routes/_dashboard.experts'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard.dashboard'
import { Route as DashboardCreditsRouteImport } from './routes/_dashboard.credits'
import { Route as AuthSignUpRouteImport } from './routes/_auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth.sign-in'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as DashboardExpertsSlugRouteImport } from './routes/_dashboard.experts.$slug'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPromptExpertsRoute = PublicPromptExpertsRouteImport.update({
  id: '/prompt-experts',
  path: '/prompt-experts',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFeaturesRoute = PublicFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExpertsRoute = DashboardExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreditsRoute = DashboardCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardExpertsSlugRoute = DashboardExpertsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DashboardExpertsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminAdminRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/credits': typeof DashboardCreditsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/experts': typeof DashboardExpertsRouteWithChildren
  '/favorites': typeof DashboardFavoritesRoute
  '/help': typeof DashboardHelpRoute
  '/history': typeof DashboardHistoryRoute
  '/settings': typeof DashboardSettingsRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/features': typeof PublicFeaturesRoute
  '/pricing': typeof PublicPricingRoute
  '/privacy': typeof PublicPrivacyRoute
  '/prompt-experts': typeof PublicPromptExpertsRoute
  '/terms': typeof PublicTermsRoute
  '/experts/$slug': typeof DashboardExpertsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminAdminRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/credits': typeof DashboardCreditsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/experts': typeof DashboardExpertsRouteWithChildren
  '/favorites': typeof DashboardFavoritesRoute
  '/help': typeof DashboardHelpRoute
  '/history': typeof DashboardHistoryRoute
  '/settings': typeof DashboardSettingsRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/features': typeof PublicFeaturesRoute
  '/pricing': typeof PublicPricingRoute
  '/privacy': typeof PublicPrivacyRoute
  '/prompt-experts': typeof PublicPromptExpertsRoute
  '/terms': typeof PublicTermsRoute
  '/experts/$slug': typeof DashboardExpertsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_admin/admin': typeof AdminAdminRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_dashboard/credits': typeof DashboardCreditsRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/experts': typeof DashboardExpertsRouteWithChildren
  '/_dashboard/favorites': typeof DashboardFavoritesRoute
  '/_dashboard/help': typeof DashboardHelpRoute
  '/_dashboard/history': typeof DashboardHistoryRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/features': typeof PublicFeaturesRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/prompt-experts': typeof PublicPromptExpertsRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/': typeof PublicIndexRoute
  '/_dashboard/experts/$slug': typeof DashboardExpertsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sign-in'
    | '/sign-up'
    | '/credits'
    | '/dashboard'
    | '/experts'
    | '/favorites'
    | '/help'
    | '/history'
    | '/settings'
    | '/contact'
    | '/faq'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/prompt-experts'
    | '/terms'
    | '/experts/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/sign-in'
    | '/sign-up'
    | '/credits'
    | '/dashboard'
    | '/experts'
    | '/favorites'
    | '/help'
    | '/history'
    | '/settings'
    | '/contact'
    | '/faq'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/prompt-experts'
    | '/terms'
    | '/experts/$slug'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/_dashboard'
    | '/_public'
    | '/_admin/admin'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_dashboard/credits'
    | '/_dashboard/dashboard'
    | '/_dashboard/experts'
    | '/_dashboard/favorites'
    | '/_dashboard/help'
    | '/_dashboard/history'
    | '/_dashboard/settings'
    | '/_public/contact'
    | '/_public/faq'
    | '/_public/features'
    | '/_public/pricing'
    | '/_public/privacy'
    | '/_public/prompt-experts'
    | '/_public/terms'
    | '/_public/'
    | '/_dashboard/experts/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/prompt-experts': {
      id: '/_public/prompt-experts'
      path: '/prompt-experts'
      fullPath: '/prompt-experts'
      preLoaderRoute: typeof PublicPromptExpertsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/features': {
      id: '/_public/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof PublicFeaturesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/history': {
      id: '/_dashboard/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/help': {
      id: '/_dashboard/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/favorites': {
      id: '/_dashboard/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/experts': {
      id: '/_dashboard/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof DashboardExpertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/credits': {
      id: '/_dashboard/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof DashboardCreditsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_dashboard/experts/$slug': {
      id: '/_dashboard/experts/$slug'
      path: '/$slug'
      fullPath: '/experts/$slug'
      preLoaderRoute: typeof DashboardExpertsSlugRouteImport
      parentRoute: typeof DashboardExpertsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardExpertsRouteChildren {
  DashboardExpertsSlugRoute: typeof DashboardExpertsSlugRoute
}

const DashboardExpertsRouteChildren: DashboardExpertsRouteChildren = {
  DashboardExpertsSlugRoute: DashboardExpertsSlugRoute,
}

const DashboardExpertsRouteWithChildren =
  DashboardExpertsRoute._addFileChildren(DashboardExpertsRouteChildren)

interface DashboardRouteChildren {
  DashboardCreditsRoute: typeof DashboardCreditsRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardExpertsRoute: typeof DashboardExpertsRouteWithChildren
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCreditsRoute: DashboardCreditsRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardExpertsRoute: DashboardExpertsRouteWithChildren,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PublicRouteChildren {
  PublicContactRoute: typeof PublicContactRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicFeaturesRoute: typeof PublicFeaturesRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicPromptExpertsRoute: typeof PublicPromptExpertsRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicContactRoute: PublicContactRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicFeaturesRoute: PublicFeaturesRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicPromptExpertsRoute: PublicPromptExpertsRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
